# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erudit', '0028_auto_20160721_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalRoyalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='royalty_reports/', verbose_name='Fichier')),
                ('published', models.BooleanField(default=False, verbose_name="Publié dans l'espace utilisateur")),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erudit.Journal', verbose_name='Revue')),
            ],
            options={
                'verbose_name': 'Redevance de revue',
                'verbose_name_plural': 'Redevances de revues',
            },
        ),
        migrations.CreateModel(
            name='RoyaltyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Date de début')),
                ('end', models.DateField(verbose_name='Date de fin')),
                ('report_file', models.FileField(upload_to='royalty_reports/', verbose_name='Fichier')),
            ],
            options={
                'verbose_name': 'Rapport de redevances',
                'verbose_name_plural': 'Rapports de redevances',
            },
        ),
        migrations.AddField(
            model_name='journalroyalty',
            name='royalty_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royalty_reports.RoyaltyReport', verbose_name='Rapport de redevances'),
        ),
    ]
