# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalty_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='royaltyreport',
            name='published',
            field=models.BooleanField(default=False, verbose_name="Publié dans l'espace utilisateur"),
        ),
        migrations.RemoveField(
            model_name='journalroyalty',
            name='published',
        ),
        migrations.AlterUniqueTogether(
            name='journalroyalty',
            unique_together=set([('royalty_report', 'journal')]),
        ),
    ]
