import random
import string

import structlog
from django.core.management.base import BaseCommand

from core.subscription.restriction.models import Abonne


def generate_sushi_id():
    SEQ = string.ascii_letters + string.digits
    return ''.join(random.choice(SEQ) for _ in range(8))


class Command(BaseCommand):
    help = "Generate SUSHI IDs in restriction DBs for all orgs that don't have any."

    # These IDs used to be generated by the legacy system but since we've moved to the new WWW,
    # new organisations being created end up with no SUSHI ID. We need to run this whenever we
    # add a new org.

    def add_arguments(self, parser):
        parser.add_argument(
            '--dry-run', action='store_true', dest='dry_run',
            help="Only list organisations that would get a new SUSHI ID"
        )

    def handle(self, *args, **options):
        logger = structlog.get_logger(__name__)
        dry_run = options['dry_run']
        targets = Abonne.objects.filter(requesterid__isnull=True)
        logger.info(
            "update.started",
            update_type="restrictions_sushi",
            to_process=targets.count(),
            dry_run=dry_run,
        )
        for target in targets.all():
            newid = generate_sushi_id()
            logger.info(
                "abonne.setsushi",
                abonneid=target.abonneid,
                newid=newid,
                dry_run=dry_run,
            )
            if not dry_run:
                target.requesterid = newid
                target.save()
        logger.info(
            "update.finished",
            update_type="restrictions_sushi",
            processed=targets.count(),
            dry_run=dry_run,
        )
