# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-28 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0004_institutionreferer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institutionreferer",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referers",
                to="subscription.JournalAccessSubscription",
                verbose_name="Abonnement aux revues",
            ),
        ),
    ]
