# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-08 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0005_auto_20170628_1323"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalaccesssubscription",
            name="journal_management_subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subscription.JournalManagementSubscription",
                verbose_name="Forfait",
            ),
        ),
    ]
