# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-14 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0006_journalaccesssubscription_journal_management_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journalaccesssubscription",
            name="full_access",
        ),
        migrations.AlterField(
            model_name="journalaccesssubscription",
            name="journal_management_subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="subscription.JournalManagementSubscription",
                verbose_name="Forfait",
            ),
        ),
    ]
