# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-02 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("subscription", "0010_journalmanagementplan_unlimited"),
        ("subscription", "0011_auto_20171002_0900"),
    ]

    dependencies = [
        ("subscription", "0009_auto_20170914_1407"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalmanagementplan",
            name="is_unlimited",
            field=models.BooleanField(default=False, verbose_name="Illimité"),
        ),
    ]
