# Generated by Django 2.0.10 on 2019-02-27 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0014_auto_20180308_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalaccesssubscription',
            name='journal',
        ),
    ]
