# Generated by Django 2.0.13 on 2019-09-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0015_remove_journalaccesssubscription_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionipaddressrange',
            name='ip_end',
            field=models.GenericIPAddressField(db_index=True, verbose_name='Adresse IP de fin'),
        ),
        migrations.AlterField(
            model_name='institutionipaddressrange',
            name='ip_start',
            field=models.GenericIPAddressField(db_index=True, verbose_name='Adresse IP de début'),
        ),
    ]
