# Generated by Django 2.0.13 on 2019-10-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0017_auto_20190926_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalaccesssubscription',
            name='is_valid',
        ),
        migrations.AddField(
            model_name='institutionipaddressrange',
            name='ip_end_int',
            field=models.IntegerField(default=1, verbose_name='Adresse IP de fin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institutionipaddressrange',
            name='ip_start_int',
            field=models.IntegerField(default=1, verbose_name='Adresse IP de début'),
            preserve_default=False,
        ),
    ]
