# Generated by Django 2.0.13 on 2019-10-16 20:54

from django.db import migrations
import ipaddress


def generate_integer_ip_addresses(apps, schema_editor):
    InstitutionIPAddressRange = apps.get_model("subscription", "InstitutionIPAddressRange")

    for range in InstitutionIPAddressRange.objects.all():
        range.ip_start_int = int(ipaddress.ip_address(range.ip_start))
        range.ip_end_int = int(ipaddress.ip_address(range.ip_end))
        range.save()


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0019_auto_20191016_1658"),
    ]

    operations = [migrations.RunPython(generate_integer_ip_addresses)]
