# Generated by Django 3.2.3 on 2021-06-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0021_auto_20191016_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalaccesssubscription',
            name='referer',
            field=models.URLField(blank=True, null=True, verbose_name='URL référent'),
        ),
    ]
