# Generated by Django 3.2.3 on 2021-06-01 22:36

from django.db import migrations


def migrate_referer_from_model_to_field(apps, schema_editor):
    InstitutionReferer = apps.get_model('subscription', 'InstitutionReferer')
    JournalAccessSubscription = apps.get_model('subscription', 'JournalAccessSubscription')
    for referer in InstitutionReferer.objects.all():
        subscription = JournalAccessSubscription.objects.get(pk=referer.subscription_id)
        subscription.referer = referer.referer
        subscription.save()


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0022_journalaccesssubscription_referer'),
    ]

    operations = [
        migrations.RunPython(migrate_referer_from_model_to_field),
    ]
