# Generated by Django 3.2.3 on 2021-06-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0024_delete_institutionreferer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JournalAccessSubscriptionPeriod',
        ),
    ]
