# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 16:52
from __future__ import unicode_literals

from django.db import migrations


def remove_persee_localidentifiers(apps, schema_editor):
    Journal = apps.get_model('erudit', 'Journal')
    Journal.objects.filter(collection__code='persee').update(localidentifier=None)

class Migration(migrations.Migration):

    dependencies = [
        ('erudit', '0064_remove_article_bibliographic_reference'),
    ]

    operations = [
        migrations.RunPython(remove_persee_localidentifiers)
    ]
