# Generated by Django 3.0.13 on 2021-03-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_message', '0003_auto_20190430_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetsite',
            name='site',
            field=models.CharField(choices=[('P', 'Public'), ('J', 'Tableau de bord des revues'), ('L', 'Tableau de bord des bibliothèques'), ('S', 'Tableau de bord des bibliothèques - Consultations')], default='P', help_text='Site cible', max_length=8, verbose_name='Site cible'),
        ),
    ]
