# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0007_alter_validators_add_error_messages"),
        ("erudit", "0017_issue_thematic_issue"),
        ("editor", "0002_issuesubmissionstatustrack_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionTeam",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "identifier",
                    models.SlugField(max_length=48, unique=True, verbose_name="Identifiant"),
                ),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.Group",
                        verbose_name="Groupe",
                    ),
                ),
                ("journals", models.ManyToManyField(to="erudit.Journal", verbose_name="Revues")),
            ],
            options={
                "verbose_name_plural": "Équipes de production",
                "verbose_name": "Équipe de production",
            },
        ),
    ]
