# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0003_productionteam"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuesubmission",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="Archivé"),
        ),
    ]
