# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0004_issuesubmission_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuesubmission",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Commentaires"),
        ),
    ]
