# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-28 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0005_auto_20160920_1037"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuesubmission",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Personne-ressource",
            ),
        ),
    ]
