# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-04 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0005_auto_20161007_0900"),
        ("editor", "0006_auto_20161028_1032"),
    ]

    operations = []
