# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-17 18:39
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0007_merge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuesubmission",
            name="status",
            field=django_fsm.FSMField(
                choices=[("D", "Brouillon"), ("S", "En attente de validation"), ("V", "Validé")],
                default="D",
                max_length=50,
            ),
        ),
    ]
