# Generated by Django 2.0.13 on 2019-09-16 13:19

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0008_auto_20180717_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuesubmission',
            name='status',
            field=django_fsm.FSMField(choices=[('D', 'Brouillon'), ('S', 'En attente de validation'), ('C', 'À corriger'), ('V', 'Validé')], default='D', max_length=50),
        ),
    ]
