# Generated by Django 2.0.13 on 2019-10-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0009_auto_20190916_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuesubmission',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaires sur le numéro'),
        ),
    ]
