# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-17 20:47
from __future__ import unicode_literals

from django.db import migrations
import isbn_field.fields
import isbn_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_auto_20180717_1541"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="digital_isbn",
            field=isbn_field.fields.ISBNField(
                blank=True,
                max_length=28,
                null=True,
                validators=[isbn_field.validators.ISBNValidator],
                verbose_name="ISBN numérique",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="isbn",
            field=isbn_field.fields.ISBNField(
                blank=True,
                max_length=28,
                null=True,
                validators=[isbn_field.validators.ISBNValidator],
                verbose_name="ISBN",
            ),
        ),
    ]
