# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0008_bookcollection"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="book.BookCollection",
            ),
        ),
        migrations.AlterField(
            model_name="bookcollection",
            name="description",
            field=models.TextField(
                blank=True, max_length=1500, null=True, verbose_name="Description de la collection"
            ),
        ),
    ]
