# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-04 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_auto_20180822_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_open_access',
            field=models.BooleanField(default=False, verbose_name='Disponible en libre accès ?'),
        ),
        migrations.AlterField(
            model_name='book',
            name='path',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Répertoire'),
        ),
    ]
