# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_auto_20180904_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Est publié ?'),
        ),
    ]
