# Generated by Django 2.0.13 on 2019-03-04 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('book', '0019_book_parent_book'), ('book', '0020_auto_20190301_1723')]

    dependencies = [
        ('book', '0018_book_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='parent_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.Book'),
        ),
    ]
