<definitions xmlns:tns="SushiService"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:sc="http://www.niso.org/schemas/sushi/counter"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             name="SushiService"
             targetNamespace="SushiService"
             xmlns="http://schemas.xmlsoap.org/wsdl/">
   <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"/>
   
   <types>
      <xsd:schema>
         <xsd:import schemaLocation="counter_sushi4_1.xsd"
                     namespace="http://www.niso.org/schemas/sushi/counter"/>
      </xsd:schema>
   </types>
   
   <message name="GetReportIn">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"/>
      <part name="messagePart"
            element="sc:ReportRequest"/>
   </message>
   
   <message name="GetReportOut">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"/>
      <part name="messagePart"
            element="sc:ReportResponse"/>
   </message>

   <portType name="SushiServiceInterface">
      <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"/>

      <operation name="GetReport">
         <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"/>
         <input message="tns:GetReportIn"/>
         <output message="tns:GetReportOut"/>
      </operation>

   </portType>

   <binding name="SushiService"
            type="tns:SushiServiceInterface">
      <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
      <operation name="GetReport">
         <soap:operation soapAction="SushiService:GetReportIn"
                         style="document"/>
         <input>
            <soap:body use="literal"/>
         </input>
         <output>
            <soap:body use="literal"/>
         </output>
      </operation>
   </binding>

   <binding name="SushiServiceSoap12"
            type="tns:SushiServiceInterface">
      <soap12:binding transport="http://schemas.xmlsoap.org/soap/http"/>
      <operation name="GetReport">
         <soap12:operation soapAction="SushiService:GetReportIn"
                           style="document"/>
         <input>
            <soap12:body use="literal"/>
         </input>
         <output>
            <soap12:body use="literal"/>
         </output>
      </operation>
   </binding>

   <service name="SushiService">
      <port name="SushiServicePort"
            binding="tns:SushiService">
         <soap:address location=""/>
      </port>
   </service>

</definitions>