# -*- coding: utf-8 -*-

import inspect
import logging
from urllib.parse import urljoin

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page
from django.utils.translation import activate
from pysolr import SolrCoreAdmin
import requests
from requests.exceptions import ConnectionError

logger = logging.getLogger(__name__)


class CacheMixin(object):
    """ Caches the result of a view for a specific number of seconds. """
    cache_timeout = 60

    def get_cache_timeout(self):
        return self.cache_timeout

    def dispatch(self, *args, **kwargs):
        return cache_page(
            self.get_cache_timeout())(super(CacheMixin, self).dispatch)(*args, **kwargs)


class MenuItemMixin(object):
    """
    This mixins injects attributes that start with the 'menu_' prefix into
    the context generated by the view it is applied to.
    This behavior can be used to highlight an item of a navigation component.
    """
    def get_context_data(self, **kwargs):
        context = super(MenuItemMixin, self).get_context_data(**kwargs)
        vattrs = inspect.getmembers(self, lambda a: not(inspect.isroutine(a)))
        menu_kwargs = dict(a for a in vattrs if a[0].startswith('menu_'))
        context.update(menu_kwargs)
        return context


class LoginRequiredMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super().as_view(**initkwargs)
        return login_required(view)


class FedoraServiceRequiredMixin(object):
    def check_fedora_status(self, request):
        """ Returns a boolean indicating if the Fedora service is available. """
        status = True
        fedora_url = urljoin(settings.FEDORA_ROOT, 'describe')
        try:
            requests.get(fedora_url, timeout=1)
        except ConnectionError:
            # The Fedora repository is not accessible!
            logger.error('Fedora repository unavailable', exc_info=True, extra={
                'request': request, })
            status = False
        return status

    def get_context_data(self, **kwargs):
        context = super(FedoraServiceRequiredMixin, self).get_context_data(**kwargs)
        context['fedora_service_available'] = self.fedora_service_available
        return context

    def dispatch(self, request, *args, **kwargs):
        self.fedora_service_available = self.check_fedora_status(request)
        return super(FedoraServiceRequiredMixin, self).dispatch(request, *args, **kwargs)


class ActivateLegacyLanguageViewMixin(object):
    """ """

    def activate_legacy_language(self, *args, **kwargs):
        if 'lang' in kwargs and kwargs['lang'] == 'en' or self.request.GET.get('lang') == 'en':
            activate('en')
        else:
            activate('fr')


class SolrServiceRequiredMixin(object):
    def check_solr_status(self, request):
        """ Returns a boolean indicating if the Solr service is available. """
        status = True
        solr_admin = SolrCoreAdmin(settings.SOLR_ADMIN)
        try:
            solr_admin.status()
        except ConnectionError:
            # The Solr index is not accessible!
            logger.error('Solr index unavailable', exc_info=True, extra={
                'request': request, })
            status = False
        return status

    def get_context_data(self, **kwargs):
        context = super(SolrServiceRequiredMixin, self).get_context_data(**kwargs)
        context['solr_service_available'] = self.solr_service_available
        return context

    def dispatch(self, request, *args, **kwargs):
        self.solr_service_available = self.check_solr_status(request)
        return super(SolrServiceRequiredMixin, self).dispatch(request, *args, **kwargs)
