# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0013_auto_20160517_1320"),
        ("erudit", "0013_organisation_members"),
    ]

    operations = []
