# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 18:10
from __future__ import unicode_literals

from django.db import migrations
import erudit.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0014_merge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="author",
        ),
        migrations.RemoveField(
            model_name="event",
            name="target_content_type",
        ),
        migrations.AlterField(
            model_name="organisation",
            name="badge",
            field=erudit.modelfields.SizeConstrainedImageField(
                blank=True, null=True, upload_to="organisation_badges", verbose_name="Badge"
            ),
        ),
        migrations.DeleteModel(
            name="Event",
        ),
    ]
