# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0016_article_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="thematic_issue",
            field=models.BooleanField(default=False, verbose_name="Numéro thématique"),
        ),
    ]
