# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0019_thesis"),
    ]

    operations = [
        migrations.AddField(
            model_name="thesis",
            name="oai_datestamp",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Datestamp OAI"),
        ),
    ]
