# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 15:47
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0002_auto_20150616_2121"),
        ("erudit", "0021_auto_20160627_1207"),
    ]

    operations = [
        migrations.AddField(
            model_name="thesis",
            name="keywords",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
