# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('erudit', '0022_thesis_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='eruditdocument',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=models.deletion.CASCADE, related_name='polymorphic_erudit.eruditdocument_set+', to='contenttypes.ContentType'),
        ),
    ]
