# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-04 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0028_auto_20160721_1517"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="othername",
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Autre nom"),
        ),
    ]
