# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-10 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0031_auto_20160808_1613"),
    ]

    operations = [
        migrations.CreateModel(
            name="Affiliation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="Nom")),
            ],
            options={
                "verbose_name": "Affiliation",
                "verbose_name_plural": "Affiliations",
            },
        ),
        migrations.AddField(
            model_name="author",
            name="affiliations",
            field=models.ManyToManyField(to="erudit.Affiliation", verbose_name="Affiliations"),
        ),
    ]
