# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-10 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0033_article_copyrights"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="name",
            field=models.CharField(max_length=600, verbose_name="Nom"),
        ),
    ]
