# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-12 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0035_auto_20160811_1442"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eruditdocument",
            name="localidentifier",
            field=models.CharField(
                db_index=True, max_length=100, unique=True, verbose_name="Identifiant unique"
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="localidentifier",
            field=models.CharField(max_length=100, unique=True, verbose_name="Identifiant Fedora"),
        ),
        migrations.AlterField(
            model_name="journal",
            name="localidentifier",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Identifiant Fedora",
            ),
        ),
    ]
