# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-30 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0043_auto_20160921_0843"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueContributor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "firstname",
                    models.CharField(max_length=255, verbose_name="Prénom du contributeur"),
                ),
                ("lastname", models.CharField(max_length=255, verbose_name="Nom du contributeur")),
                (
                    "role_name",
                    models.CharField(max_length=255, verbose_name="Rôle du contributeur"),
                ),
                ("is_director", models.NullBooleanField(verbose_name="Est un directeur")),
                ("is_editor", models.NullBooleanField(verbose_name="Est un rédacteur")),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="contributors",
                        to="erudit.Issue",
                        verbose_name="Numéro",
                    ),
                ),
            ],
        ),
    ]
