# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-04 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0044_issuecontributor"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuecontributor",
            name="role_name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Rôle du contributeur"),
        ),
        migrations.AddField(
            model_name="issuecontributor",
            name="role_name_fr",
            field=models.CharField(max_length=255, null=True, verbose_name="Rôle du contributeur"),
        ),
    ]
