# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-04 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0046_auto_20161004_1516"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuecontributor",
            name="lastname",
            field=models.CharField(max_length=255, null=True, verbose_name="Nom du contributeur"),
        ),
    ]
