# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-14 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0047_auto_20161004_1530"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issuecontributor",
            name="role_name_en",
        ),
        migrations.RemoveField(
            model_name="issuecontributor",
            name="role_name_fr",
        ),
    ]
