# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-14 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0048_auto_20161014_1616"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuecontributor",
            name="role_name",
            field=models.CharField(max_length=255, null=True, verbose_name="Rôle du contributeur"),
        ),
    ]
