# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-26 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0051_auto_20161020_1256"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="bibliographic_reference",
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="type",
            field=models.CharField(
                choices=[
                    ("article", "Article"),
                    ("compterendu", "Compte rendu"),
                    ("compterendu", "Note"),
                    ("autre", "Autre"),
                ],
                max_length=64,
                verbose_name="Type",
            ),
        ),
    ]
