# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-28 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0054_auto_20161028_1036"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="title",
        ),
    ]
