# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-28 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0057_auto_20161123_1703"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="subtitle",
        ),
    ]
