# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0059_auto_20161212_1038"),
        ("erudit", "0057_auto_20161221_1449"),
    ]

    operations = []
