# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0060_merge_20170112_1048"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="journals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Membres",
            ),
        ),
    ]
