# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0061_auto_20170112_1048"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
