# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0062_issue_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Est publié"),
        ),
    ]
