# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-18 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0069_auto_20170418_1227"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="publication_allowed_by_authors",
        ),
        migrations.AddField(
            model_name="article",
            name="publication_allowed",
            field=models.BooleanField(
                default=True,
                verbose_name="Publication autorisée par le titulaire du droit d'auteur",
            ),
        ),
    ]
