# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0070_auto_20170418_1228"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journal",
            name="upcoming",
        ),
    ]
