# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-11 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0073_article_formatted_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="is_new",
            field=models.BooleanField(
                default=False,
                help_text="Cocher si cette revue est nouvelle sur la plateforme d'Érudit.",
                verbose_name="Est une nouveauté",
            ),
        ),
    ]
