# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-05 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0076_auto_20171005_0938"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="legacyorganisationprofile",
            options={"verbose_name": "Compatibilité avec la base de données restriction"},
        ),
        migrations.AlterField(
            model_name="legacyorganisationprofile",
            name="sushi_requester_id",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Identifiant SUSHI"
            ),
        ),
    ]
