# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-16 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0077_auto_20171005_1003"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="formatted_volume_title",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Informations de volumaison"
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="formatted_volume_title_en",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Informations de volumaison"
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="formatted_volume_title_fr",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Informations de volumaison"
            ),
        ),
    ]
