# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-08 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0078_auto_20171116_1721"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journal",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="journal",
            name="name_fr",
        ),
        migrations.RemoveField(
            model_name="journal",
            name="subtitle_en",
        ),
        migrations.RemoveField(
            model_name="journal",
            name="subtitle_fr",
        ),
    ]
