# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-17 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0079_auto_20180108_1119"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="language",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Code langue"
            ),
        ),
    ]
