# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-01 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0080_auto_20180117_1526"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuecontributor",
            name="role_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Rôle du contributeur"
            ),
        ),
    ]
