# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-09 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0083_auto_20180308_0922"),
        ("erudit", "0083_auto_20180307_1012"),
    ]

    operations = []
