# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-21 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0085_auto_20180320_1437"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlesectiontitle",
            name="article",
        ),
        migrations.RemoveField(
            model_name="articlesubtitle",
            name="article",
        ),
        migrations.RemoveField(
            model_name="articletitle",
            name="article",
        ),
        migrations.DeleteModel(
            name="ArticleSectionTitle",
        ),
        migrations.DeleteModel(
            name="ArticleSubtitle",
        ),
        migrations.DeleteModel(
            name="ArticleTitle",
        ),
    ]
