# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-21 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0086_auto_20180321_0717"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articleabstract",
            name="article",
        ),
        migrations.DeleteModel(
            name="ArticleAbstract",
        ),
    ]
