# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-21 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0087_auto_20180321_0853"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="copyrights",
        ),
    ]
