# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-01 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0089_thesisprovider"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thesis",
            name="author",
        ),
        migrations.RemoveField(
            model_name="thesis",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="thesis",
            name="eruditdocument_ptr",
        ),
        migrations.DeleteModel(
            name="Thesis",
        ),
    ]
