# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-01 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0089_thesisprovider"),
        ("erudit", "0089_auto_20180419_0825"),
    ]

    operations = []
