# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-01 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0091_auto_20180501_0854"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="keywordtaggedwhatever",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="keywordtaggedwhatever",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="eruditdocument",
            name="keywords",
        ),
        migrations.DeleteModel(
            name="KeywordTag",
        ),
        migrations.DeleteModel(
            name="KeywordTaggedWhatever",
        ),
    ]
