# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-01 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0092_auto_20180501_0915"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issuecontributor",
            name="issue",
        ),
        migrations.DeleteModel(
            name="IssueContributor",
        ),
    ]
