# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-02 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0092_auto_20180501_0915"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ThesisProvider",
            new_name="ThesisRepository",
        ),
        migrations.AlterModelOptions(
            name="thesisrepository",
            options={
                "verbose_name": "Dépôt institutionnel",
                "verbose_name_plural": "Dépôts institutionnels",
            },
        ),
    ]
