# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-02 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0090_merge_20180501_0913"),
        ("erudit", "0093_auto_20180502_1343"),
    ]

    operations = []
