# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-01 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0094_auto_20180501_1056"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="formatted_volume_title",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="formatted_volume_title_en",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="formatted_volume_title_fr",
        ),
    ]
