# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-01 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0095_auto_20180501_1106"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="copyrights",
        ),
        migrations.DeleteModel(
            name="Copyright",
        ),
    ]
