# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-03 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0094_merge_20180502_1413"),
        ("erudit", "0096_auto_20180501_1116"),
    ]

    operations = []
