# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-08 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erudit', '0097_merge_20180508_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='eruditdocument_ptr',
        ),
        migrations.RemoveField(
            model_name='article',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='eruditdocument',
            name='polymorphic_ctype',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='EruditDocument',
        ),
    ]
