# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-17 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erudit', '0097_merge_20180503_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalinformation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Adresse courriel pour demandes générales'),
        ),
        migrations.AlterField(
            model_name='journalinformation',
            name='subscription_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Adresse courriel pour abonnements individuels'),
        ),
    ]
