# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erudit', '0098_auto_20180717_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='eruditdocument_ptr',
        ),
        migrations.RemoveField(
            model_name='article',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='eruditdocument',
            name='polymorphic_ctype',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='EruditDocument',
        ),
    ]
