# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0103_auto_20181029_1416"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journal",
            name="issues_per_year",
        ),
    ]
