# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0104_remove_journal_issues_per_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="role",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Rôle"),
        ),
    ]
