# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erudit', '0106_auto_20181122_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='date_produced',
        ),
    ]
