# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0107_remove_issue_date_produced"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journal",
            name="website_url",
        ),
    ]
