# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0108_remove_journal_website_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issue",
            old_name="title",
            new_name="_title",
        ),
    ]
