# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0109_auto_20181123_1427"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issue",
            old_name="first_page",
            new_name="_first_page",
        ),
        migrations.RenameField(
            model_name="issue",
            old_name="html_title",
            new_name="_html_title",
        ),
        migrations.RenameField(
            model_name="issue",
            old_name="last_page",
            new_name="_last_page",
        ),
    ]
