# Generated by Django 2.0.13 on 2019-03-28 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erudit', '0112_organisation_google_scholar_opt_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='type',
            field=models.ForeignKey(default='S', on_delete=django.db.models.deletion.CASCADE, to='erudit.JournalType', verbose_name='Type'),
        ),
    ]
