# Generated by Django 2.0.13 on 2019-09-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erudit', '0115_journalinformation_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='charges_apc',
            field=models.BooleanField(default=False, help_text='Cocher si la revue charge des frais de publications (APC) aux auteurs', verbose_name='Frais de publication (APC)'),
        ),
    ]
