# Generated by Django 3.0.7 on 2020-09-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erudit', '0119_journal_special_open_access_opt_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='special_open_access_opt_in',
        ),
    ]
