# Generated by Django 3.0.11 on 2021-01-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erudit", "0120_remove_journal_special_open_access_opt_in"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organisation",
            name="city",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="country",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="province",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="street",
        ),
    ]
