# Generated by Django 3.0.11 on 2021-01-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erudit', '0122_add_legacy_fields_to_organisation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LegacyOrganisationProfile',
        ),
    ]
