# Generated by Django 3.0.13 on 2021-03-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erudit', '0123_delete_legacyorganisationprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalinformation',
            name='organisation_name',
        ),
    ]
