# Generated by Django 3.2 on 2021-04-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erudit', '0124_remove_journalinformation_organisation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='paper',
            field=models.BooleanField(default=None, help_text='Est publiée également en version papier?', null=True, verbose_name='Papier'),
        ),
    ]
