# Generated by Django 3.0.13 on 2021-03-23 17:44

from django.db import migrations


def refactor_languages_field(apps, schema_editor):
    # We can't import the JournalInformation model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    JournalInformation = apps.get_model('erudit', 'JournalInformation')
    for journal_info in JournalInformation.objects.all():
        # If journal has French and English in their `languages` field adopt "FA" as default
        if journal_info.languages.filter(id__in=["1", "2"]).count() == 2:
            journal_info.main_languages = "FA"
        elif journal_info.languages.filter(id__in=["2"]).count() == 1:
            journal_info.main_languages = "A"
        journal_info.other_languages.set(journal_info.languages.exclude(id__in=["1", "2"]))
        journal_info.save()


class Migration(migrations.Migration):

    dependencies = [
        ('erudit', '0125_auto_20210323_1340'),
    ]

    operations = [
        migrations.RunPython(refactor_languages_field),
    ]
