# Generated by Django 3.0.13 on 2021-03-23 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erudit', '0126_auto_20210323_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalinformation',
            name='languages',
        ),
    ]
