# Generated by Django 3.2.3 on 2021-06-01 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erudit', '0125_alter_journal_paper'),
        ('erudit', '0127_remove_journalinformation_languages'),
    ]

    operations = [
    ]
