# Generated by Django 3.2.3 on 2021-06-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erudit', '0128_discipline_type'),
        ('erudit', '0128_merge_20210601_1147'),
    ]

    operations = [
    ]
