# Generated by Django 3.2.3 on 2021-06-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erudit', '0129_merge_0128_discipline_type_0128_merge_20210601_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='type',
        ),
        migrations.AddField(
            model_name='discipline',
            name='type',
            field=models.ManyToManyField(to='erudit.JournalType', verbose_name='Type'),
        ),
    ]
