# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erudit', '0024_auto_20160629_0944'),
        ('citations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedcitationlist',
            name='articles',
        ),
        migrations.AddField(
            model_name='savedcitationlist',
            name='documents',
            field=models.ManyToManyField(to='erudit.EruditDocument', verbose_name='Documents Érudit'),
        ),
    ]
