# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-05 12:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def transfer_citations(apps, schema_editor):
    SavedCitation = apps.get_model('citations.SavedCitation')
    SavedCitationList = apps.get_model('citations.SavedCitationList')
    # WARNING: not a good practice for migrations!
    # Directly refering to "live" models in migrations is a bad practice, but
    # when we don't, we don't have access to models methods, which would make
    # us have to copy/paste too much code to make this work.
    # This migration has to be applied on all systems *before* we change any
    # of the EruditDocument models, otherwise it will fail.
    # Once all systems are migrated, the best thing to do would be to remove
    # data migration entirely.
    from erudit.models import EruditDocument
    for cl in SavedCitationList.objects.all():
        for doc in cl.documents.all():
            doc = EruditDocument.objects.get(id=doc.id)
            solr_id = doc.get_real_instance().solr_id
            SavedCitation.objects.get_or_create(user=cl.user, solr_id=solr_id)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('citations', '0002_auto_20160629_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solr_id', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_citations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='savedcitation',
            unique_together=set([('user', 'solr_id')]),
        ),
        migrations.RunPython(transfer_citations),
    ]
