# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-10 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0003_auto_20180405_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedcitationlist',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='savedcitationlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='SavedCitationList',
        ),
    ]
