# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auto_20160705_1038"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legacyaccountprofile",
            name="origin",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Base de données Abonnements"),
                    (2, "Base de données Restrictions"),
                    (3, "Base de données Mandragore"),
                    (4, "Base de données Drupal"),
                ],
                verbose_name="Origine",
            ),
        ),
    ]
