# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 14:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20160705_1430"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legacyaccountprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
    ]
