#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /opt/eruditorg/eruditorg/manage.py collectstatic --noinput
/usr/local/bin/gunicorn \
    -b 0.0.0.0:8000 \
    --pythonpath /opt/eruditorg/eruditorg \
    --access-logfile "-" \
    --error-logfile "-" \
    eruditorg.wsgi
