# Force the use of the new container-based infrastructure
sudo: false

language: python
python:
  - "3.4"
  - "3.5"
env:
  - DJANGO="django>=1.10,<1.11"
  - DJANGO="django>=1.11"

matrix:
  exclude:
  - python: "3.3"
before_install:
  - "pip install --upgrade pytest"
install:
  - "pip install $DJANGO"
script:
  - make travis
after_success:
  - codecov
